#lang sicp

; Exercise 1.15
; https://mitpress.mit.edu/sites/default/files/sicp/full-text/book/book-Z-H-11.html#%_thm_1.15
;
; The sine of an angle (specified in radians) can be computed by making use of
; the approximation sin(x) ≈ x if x is sufficiently small, and the
; trigonometric identity
;     sin(x) = 3sin(x^3) − 4sin^3(x^3)
; to reduce the size of the argument of sin. (For purposes of this exercise an
; angle is considered “sufficiently small” if its magnitude is not greater
; than 0.1 radians.) These ideas are incorporated in the following procedures:

(define (cube x) (* x x x))
(define (p x) (- (* 3 x) (* 4 (cube x))))
(define (sine angle)
   (if (not (> (abs angle) 0.1))
       angle
       (p (sine (/ angle 3.0)))))

; 1. How many times is the procedure p applied when (sine 12.15) is evaluated?
;
; 2. What is the order of growth in space and number of steps (as a function
;    of a) used by the process generated by the sine procedure when (sine a)
;    is evaluated?

; 1. 5 times, since 12.15/3^5 = 0.05.
;
; 2. It's proportional to the depth of the tree, so Θ(log n), since n is
; divided by 3 for every call.
